### ISSUE TITLE
第二篇过时了，希望能跟上源头修订。

### ISSUE THREAD

**Issue by ssrlive** [rustcc/writing-an-os-in-rust#17]
如题。非常期待。

**Comment by luojia65** [comment]
有点不想搞了，贸易战开始，身边的组织都放弃了继续投资x86、arm系技术，包括我这本书，如果有兴趣欢迎PR。真的对这系列书感兴趣，去翻一翻rCore的教程，知识都新很多

**Comment by ssrlive** [comment]
感谢。
