### ISSUE TITLE
在做第二篇的时候cargo bootimage出现了报错

### ISSUE THREAD

**Issue by zhougit86** [rustcc/writing-an-os-in-rust#18]
error: the legacy LLVM-style asm! syntax is no longer supported
  --> /Users/zhouxiaogang/.cargo/registry/src/github.com-1ecc6299db9ec823/x86_64-0.8.3/src/registers/mod.rs:13:9
   |
13 |           asm!(
   |           ^---
   |           |
   |  _________help: replace with: `llvm_asm!`
   | |
14 | |             "lea (%rip), $0"
15 | |             : "=r"(rip) ::: "volatile"
16 | |         );
   | |__________^
   |
   = note: consider migrating to the new asm! syntax specified in RFC 2873
   = note: alternatively, switch to llvm_asm! to keep your code working as it is

**Comment by luojia65** [comment]
由于贸易战，这个系列的x86开发文章已经不再更新了。你可以关注清华的rCore系统开发教程。
